# Generated by Django 2.2 on 2019-04-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('memory', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('operating_system', models.TextField()),
                ('cpu', models.TextField()),
                ('display_size', models.FloatField()),
                ('pixels_per_inch', models.IntegerField()),
                ('duble_camera', models.BooleanField()),
                ('number_of_SIM_cards', models.IntegerField()),
                ('SIM_card_type', models.TextField()),
                ('moisture_protection', models.BooleanField()),
            ],
            options={
                'ordering': ['brand', 'model', 'memory'],
            },
        ),
        migrations.CreateModel(
            name='IPhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('digital_zoom', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('A_GPS_module', models.BooleanField()),
                ('memory_card_support', models.TextField()),
                ('max_size_memory_card', models.IntegerField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('graphic_accelerator', models.TextField()),
            ],
            bases=('phones.phone',),
        ),
    ]
