# Generated by Django 2.2 on 2019-04-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190413_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compilation',
            options={'ordering': ['is_main'], 'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
    ]
