# Generated by Django 2.2 on 2019-04-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190414_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compilation',
            options={'ordering': ['-is_main', 'category'], 'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
    ]
