# Generated by Django 2.2 on 2019-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=150, verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Путь до файла',
                'verbose_name_plural': 'Пути до файлов',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('width', models.IntegerField(verbose_name='Ширина поля')),
                ('serial_number', models.IntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
    ]
