# Generated by Django 2.2 on 2019-09-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepath',
            name='file_path',
        ),
        migrations.AddField(
            model_name='filepath',
            name='file_name',
            field=models.CharField(default='', max_length=150, verbose_name='Имя файла'),
        ),
    ]
