# Generated by Django 2.2 on 2019-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20190911_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepath',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Файл выбран'),
        ),
    ]
