# Generated by Django 2.2 on 2019-09-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_filepath_is_selected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['serial_number'], 'verbose_name': 'Поле', 'verbose_name_plural': 'Поля'},
        ),
    ]
