# Generated by Django 2.2 on 2019-04-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pub_date']},
        ),
    ]
